### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by VictorTaelin** [tom-doerr/vim_codex#11]
I'm having a weird error. The package was worked fine until a few days ago. Suddenly, it stopped working, and, whenever I launch VIM, I get the following message:

```
v@v-2 ~/.vim/bundle/vim_codex$ vim
Error detected while processing /Users/v/.vim/bundle/vim_codex/plugin/vim_codex.vim:
line   21:
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/Users/v/.vim/bundle/vim_codex/python/plugin.py", line 14, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
```

I believe this error started when I installed LLVM on my system. Running `pip3 install openai` succeeds, but doesn't solve the problem:

```
v@v-2 ~/.vim/bundle/vim_codex$ pip3 install openai
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: openai in /opt/homebrew/lib/python3.9/site-packages (0.10.4)
Requirement already satisfied: pandas>=1.2.3 in /opt/homebrew/lib/python3.9/site-packages (from openai) (1.3.3)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /opt/homebrew/lib/python3.9/site-packages (from openai) (1.2.0.17)
Requirement already satisfied: requests>=2.20 in /opt/homebrew/lib/python3.9/site-packages (from openai) (2.26.0)
Requirement already satisfied: tqdm in /opt/homebrew/lib/python3.9/site-packages (from openai) (4.62.3)
Requirement already satisfied: openpyxl>=3.0.7 in /opt/homebrew/lib/python3.9/site-packages (from openai) (3.0.9)
Requirement already satisfied: et-xmlfile in /opt/homebrew/lib/python3.9/site-packages (from openpyxl>=3.0.7->openai) (1.1.0)
Requirement already satisfied: numpy>=1.17.3 in /opt/homebrew/lib/python3.9/site-packages (from pandas>=1.2.3->openai) (1.21.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/homebrew/lib/python3.9/site-packages (from pandas>=1.2.3->openai) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /opt/homebrew/lib/python3.9/site-packages (from pandas>=1.2.3->openai) (2021.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.9/site-packages (from requests>=2.20->openai) (2021.5.30)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/homebrew/lib/python3.9/site-packages (from requests>=2.20->openai) (2.0.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.9/site-packages (from requests>=2.20->openai) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.9/site-packages (from requests>=2.20->openai) (3.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas>=1.2.3->openai) (1.16.0)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
```

Moreover, if I create a normal Python file with `import openai`, it works fine. So, it seems like the Python used by VIM is somehow different, and can't find the openai library anymore. Why could that be?

**Comment by VictorTaelin** [comment]
The issue was indeed that LLVM installed a different version of Python; I had both 3.9 and 3.10 installed. Telling homebrew to unlink/link Python3 solved the issue.
