### ISSUE TITLE
Error trying to use autocomplete 

### ISSUE THREAD

**Issue by thiago-scherrer** [tom-doerr/vim_codex#4]
Hello!
Nice work!!

# My config:
## vim 

```sh
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep  2 2021 15:35:57)
Correções incluídas: 1-3397
+python3 
```
## OS

- Debian GNU/Linux 11
- 5.10.0-8-amd64 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

## Problem

I'm trying to use the plugin, but the error below occurs when I call auto complete:

```sh
Traceback (most recent call last):
  File "/home/myUserHere/.vim/plugged/vim_codex/python/plugin.py", line 27, in complete_input
    response = complete_input_max_length(input_prompt, int(2.5 * MAX_SUPPORTED_INPUT_LENGTH), stop=stop)

  File "/home/myUserHere/.vim/plugged/vim_codex/python/plugin.py", line 22, in complete_input_max_le
ngth
    response = openai.Completion.create(engine='davinci-codex', prompt=input_prompt, best_of=1, temperat
ure=0.5, max_tokens=64, stream=USE_STREAM_FEATURE, stop=stop)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/completion.py", line 31, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/abstract/engine_api_resource.py", li
ne 66, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 129, in request
    resp = self.interpret_response(rbody, rcode, rheaders, stream=stream)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 348, in interpret_response

    return self.interpret_response_line(rbody, rcode, rheaders, stream)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 367, in interpret_response
_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Engine not found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/myUserHere/.vim/plugged/vim_codex/python/plugin.py", line 43, in create_completion
    response = complete_input(input_prompt, stop=stop)
  File "/home/myUserHere/.vim/plugged/vim_codex/python/plugin.py", line 29, in complete_input
    response = complete_input_max_length(input_prompt, MAX_SUPPORTED_INPUT_LENGTH, stop=stop)
  File "/home/myUserHere/.vim/plugged/vim_codex/python/plugin.py", line 22, in complete_input_max_le
ngth
    response = openai.Completion.create(engine='davinci-codex', prompt=input_prompt, best_of=1, temperat
ure=0.5, max_tokens=64, stream=USE_STREAM_FEATURE, stop=stop)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/completion.py", line 31, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/abstract/engine_api_resource.py", li
ne 66, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 129, in request
    resp = self.interpret_response(rbody, rcode, rheaders, stream=stream)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 348, in interpret_response

    return self.interpret_response_line(rbody, rcode, rheaders, stream)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 367, in interpret_response
_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Engine not found
```

**Comment by tom-doerr** [comment]
Are you sure that your API key gives you access to OpenAI Codex? Just having access to the OpenAI API is not enough, you also need to be accepted for Codex.

**Comment by thiago-scherrer** [comment]
I just looked at my email =>

`You're still on the waitlist for Codex. You'll receive a separate email when we're ready for you to try it out`

You are absolutely right. Thanks for the help and the quick response!
I will close the issue, thanks!
